server:
  port: 8080
  servlet:
    context-path: /xa
spring:
  profiles:
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://10.193.149.201:30714/new_ihp_media?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: pass
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 50
      auto-commit: true
      pool-name: XaLifeHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


